utilisateur:
    path:     /
    defaults: { _controller: "XmUserBundle:User:index" }

utilisateur_show:
    path:     /{id}/show
    defaults: { _controller: "XmUserBundle:User:show" }

utilisateur_new:
    path:     /new
    defaults: { _controller: "XmUserBundle:User:new" }

utilisateur_create:
    path:     /create
    defaults: { _controller: "XmUserBundle:User:create" }
    methods:  POST

utilisateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "XmUserBundle:User:edit" }

utilisateur_update:
    path:     /{id}/update
    defaults: { _controller: "XmUserBundle:User:update" }
    methods:  [POST, PUT]

utilisateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "XmUserBundle:User:delete" }
    methods:  [POST, DELETE]
